environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYVER: "3.5"
    - PYTHON: "C:\\Python36"
      PYVER: "3.6"
    - PYTHON: "C:\\Python37"
      PYVER: "3.7"
    - PYTHON: "C:\\Python35-x64"
      PYVER: "3.5"
    - PYTHON: "C:\\Python36-x64"
      PYVER: "3.6"
    - PYTHON: "C:\\Python37-x64"
      PYVER: "3.7"

build: false

install:
  - python -m pip install xmltodict

test_script:
  - python --version
  - python setup.py test
